name: Run Modrinth Tracker Bot

on:
  schedule:
    - cron: '0 * * * *' # Wakes up automatically every single hour
  workflow_dispatch: # Allows you to press a button to test it instantly

permissions:
  contents: write # Allows the bot to write history to prevent duplicate alerts

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true" # Clears the Node.js warning layout

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository Code
      uses: actions/checkout@v4

    - name: Set Up Python Environment
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: pip install requests

    - name: Run Script and Check Updates
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python Discord/bot.py  # Points directly to your script inside the Discord folder

    - name: Save Cache for Next Run
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update last posted pack cache [skip ci]"
        file_pattern: 'Discord/last_posted_project.txt' # Saves cache inside your Discord folder
